@API_TRANSPORTISTE_HostAddress = http://localhost:5025

GET {{API_TRANSPORTISTE_HostAddress}}/api/transportista/1/ciudades
Accept: application/json

###

GET {{API_TRANSPORTISTE_HostAddress}}/api/transportista/1/rutas
Accept: application/json

###
GET {{API_TRANSPORTISTE_HostAddress}}/api/transportista/1/buses
Accept: application/json

###

GET {{API_TRANSPORTISTE_HostAddress}}/api/transportista/1/programaciones?Fecha=2026-01-13&IdOrigen=2090&IdDestino=2340
Accept: application/json

###

GET {{API_TRANSPORTISTE_HostAddress}}/api/transportista/TipoAsiento